use latest, add upgrade tests

diff --git a/.github/workflows/pimcore-demo.yml b/.github/workflows/pimcore-demo.yml
--- a/.github/workflows/pimcore-demo.yml
+++ b/.github/workflows/pimcore-demo.yml
@@ -19,11 +19,10 @@ jobs:
     strategy:
         matrix:
             include:
-                - { php-version: 8.1, database: "mariadb:10.3", dependencies: lowest, pimcore_version: "", experimental: false }
-                - { php-version: 8.2, database: "mariadb:10.7", dependencies: highest, pimcore_version: "", experimental: false }
-                - { php-version: 8.2, database: "mariadb:10.7", dependencies: highest, pimcore_version: "11.x-dev as 11.0.0", experimental: true }
-                - { php-version: 8.2, database: "mysql:latest", dependencies: highest, pimcore_version: "", experimental: false }
-                - { php-version: 8.2, database: "mysql:latest", dependencies: highest, pimcore_version: "11.x-dev as 11.0.0", experimental: true }
+                - { php-version: 8.2, database: "mariadb:latest", pimcore_version: "", pimcore_upgrade_version: "11.x-dev as 11.0.0", experimental: false }
+                - { php-version: 8.2, database: "mariadb:latest", pimcore_version: "11.x-dev as 11.0.0", experimental: true }
+                - { php-version: 8.2, database: "mysql:latest", pimcore_version: "", pimcore_upgrade_version: "11.x-dev as 11.0.0", experimental: false }
+                - { php-version: 8.2, database: "mysql:latest", pimcore_version: "11.x-dev as 11.0.0", experimental: true }
     steps:
     # Check out the repo in a sub-dir to see if it can serve as
     # template for `composer create-project`
@@ -77,6 +76,7 @@ jobs:
       continue-on-error: true
       env:
           PIMCORE_VERSION: "${{ matrix.pimcore_version }}"
+          UPGRADE_VERSION: "${{ matrix.pimcore_upgrade_version }}"
           DOCKER_DATABASE: "${{ matrix.database }}"
       run: |
         # Echo commands and terminate on first error
@@ -121,4 +121,18 @@ jobs:
            echo "Install failed, skipping build"
            exit 1;
         fi
+          
+        if [ ! -z "$UPGRADE_VERSION" ]; then
+          docker-compose exec -T -- php composer require pimcore/pimcore:"${UPGRADE_VERSION}"
+          
+          # Check if website is reachable, after compsoser upgrade
+          response=$(docker-compose exec -T -- php bash -c 'curl -s "nginx:80"')
+          
+          if [[ ! $response =~ "Satisfaction" ]]; then
+             echo "Install failed, skipping build"
+             exit 1;
+          fi
+          
+        fi  
+          
         docker-compose down -v --remove-orphans
