refactor with a `if`, use maria specific version to test

diff --git a/.github/workflows/pimcore-demo.yml b/.github/workflows/pimcore-demo.yml
--- a/.github/workflows/pimcore-demo.yml
+++ b/.github/workflows/pimcore-demo.yml
@@ -20,8 +20,8 @@ jobs:
     strategy:
         matrix:
             include:
-                - { php-version: 8.2, database: "mariadb:latest", pimcore_version: "", experimental: true }
-                - { php-version: 8.2, database: "mariadb:latest", pimcore_version: "", pimcore_upgrade_version: "11.x-dev as 11.0.0", experimental: true }
+                - { php-version: 8.2, database: "mariadb:10.9", pimcore_version: "", experimental: true }
+                - { php-version: 8.2, database: "mariadb:10.9", pimcore_version: "", pimcore_upgrade_version: "11.x-dev as 11.0.0", experimental: true }
                 - { php-version: 8.2, database: "mysql:latest", pimcore_version: "", experimental: true }
                 - { php-version: 8.2, database: "mysql:latest", pimcore_version: "", pimcore_upgrade_version: "11.x-dev as 11.0.0", experimental: true }
     steps:
@@ -122,18 +122,17 @@ jobs:
         fi
 
     - name: Test pimcore upgrade
+      if: ${{ matrix.pimcore_upgrade_version != '' }}
       env:
           UPGRADE_VERSION: "${{ matrix.pimcore_upgrade_version }}"
       run: |
         cd sample-project/
-        if [ ! -z "$UPGRADE_VERSION" ]; then
-          docker-compose exec -T -- php composer require pimcore/pimcore:"${UPGRADE_VERSION}"
-          # Check if website is reachable, after compsoser upgrade
-          response=$(docker-compose exec -T -- php bash -c 'curl -s "nginx:80"')
-          if [[ ! $response =~ "Satisfaction" ]]; then
-             echo "Install failed, skipping build"
-             exit 1;
-          fi
+        docker-compose exec -T -- php composer require pimcore/pimcore:"${UPGRADE_VERSION}"
+        # Check if website is reachable, after upgrade
+        response=$(docker-compose exec -T -- php bash -c 'curl -s "nginx:80"')
+        if [[ ! $response =~ "Satisfaction" ]]; then
+           echo "Install failed, skipping build"
+           exit 1;
         fi
 
     - name: Compose down
